# When the node of running CronJob is down, Job recreated new CronJob pod. This caused duplicates.
# To not retry a failed CronJob and to not recreate new CronJob pod
# following specs are applied as a whole: concurrencyPolicy, failedJobsHistoryLimit, backoffLimit, restartPolicy
# Ref: https://stackoverflow.com/a/51687712/6123088 
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: spider
  name: cron-spider-queues
spec:
  schedule: "*/12 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: spider-account
          containers:
          - name: cms-htcondor-es
            image: cmssw/cms-htcondor-es:d1dfe4d
            imagePullPolicy: Always
            args:
            - python
            - /cms-htcondor-es/celery_spider_cms.py
            #- --dry_run
            - --feed_es
            - --query_queue_batch_size
            - "500"
            - --amq_bunch_size
            - "500"
            env: &spider_env
              - name: AFFILIATION_DIR_LOCATION
                value: /cms_shared/affiliation_dir.json
              - name: CELERY_BROKER_URL
                value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT_6379)/0
              - name: CELERY_RESULT_BACKEND
                value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT_6379)/1
              - name: CELERY_TEST
                value: '"false"'
              - name: CMS_AMQ_PASSWORD_FILE
                value: /cms_secrets/amq-password/amq-password
              - name: CMS_AMQ_USERNAME_FILE
                value: /cms_secrets/amq-username/amq-username
              - name: CMS_ES_CONF_FILE
                value: /cms_secrets/es-conf/es-conf
              - name: CMS_HTCONDOR_BROKER
                value: cms-test-mb.cern.ch
              - name: CMS_HTCONDOR_PRODUCER
                value: condor-test
              - name: CMS_HTCONDOR_TOPIC
                value: /topic/cms.jobmon.condor
              - name: COLLECTORS_FILE_LOCATION
                value: /cms_secrets/collectors/collectors
              - name: C_FORCE_ROOT
                value: '"true"'
              - name: PYTHONPATH
                value: /cms-htcondor-es/src:$PYTHONPATH
              - name: REQUESTS_CA_BUNDLE
                value: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
              - name: SPIDER_CHECKPOINT
                value: redis://$(REDIS_CHECKPOINT_SERVICE_HOST):$(REDIS_CHECKPOINT_SERVICE_PORT)/0
            volumeMounts:  &spider_mounts
              - name: amq-username
                mountPath: /cms_secrets/amq-username
              - name: amq-password
                mountPath: /cms_secrets/amq-password
              - name: es-conf
                mountPath: /cms_secrets/es-conf
              - name: collectors
                mountPath: /cms_secrets/collectors
              - name: spider-shared-ceph-claim
                mountPath: /cms_shared
          restartPolicy: Never
          securityContext:
            fsGroup: 1414
          volumes:  &spider_volumes
            - name: amq-username
              secret:
                items:
                - key: amq-username
                  path: amq-username
                secretName: amq-username
            - name: amq-password
              secret:
                items:
                - key: amq-password
                  path: amq-password
                secretName: amq-password
            - name: es-conf
              secret:
                items:
                - key: es-conf
                  path: es-conf
                secretName: es-conf
            - name: collectors
              secret:
                items:
                - key: collectors
                  path: collectors
                secretName: collectors
            - name: spider-shared-ceph-claim
              persistentVolumeClaim:
                claimName: spider-ceph-claim
                readOnly: false
