
replicaCount: 1

image:
  repository: cmssw/exitcodes
  pullPolicy: Always
  tag: "HG2011h-c"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9201

ingress:
  enabled: true
  annotationsProd:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
  hosts:
    - host: cmsweb-test8.cern.ch #ingress.hosts[0].host= ""
      paths: 
      - /exitcodes
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
   limits:
     cpu: 300m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  httpGet:
            path: /exitcodes/status
            port: 9201
nodeSelector: {}

tolerations: []

affinity: {}
