apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spider-flower
  name: spider-flower
  namespace: spider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spider-flower
  strategy: {}
  template:
    metadata:
      labels:
        app: spider-flower
    spec:
      containers:
      - args:
        - celery
        - flower
        - --broker=redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT_6379)/0
        - --port=5555
        - -A=htcondor_es.celery.celery
        - -l=DEBUG
        - --persistent=True
        - --max_tasks=1000000000
        - --db=/cms_shared/flower.db
        image: cmssw/cms-htcondor-es:d1dfe4d
        name: spider-flower
        ports:
        - containerPort: 5555
          name: port-5555
        resources:
          limits:
            cpu: 300m
            memory: 1Gi
          requests:
             cpu: 100m
             memory: 100Mi
        volumeMounts:
          - name: spider-shared-ceph-claim
            mountPath: /cms_shared
      volumes:
        - name: spider-shared-ceph-claim
          persistentVolumeClaim:
            claimName: spider-ceph-claim
            readOnly: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
status: {}
