apiVersion: v1
kind: ConfigMap
metadata:
  name: das-server-filebeat-config
  namespace: das
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /data/logs/das.log*${MY_POD_NAME}*
      ignore_older: 1h
      scan_frequency: 10s
      backoff: 5s
      max_backoff: 10s
    output.console:
      codec.format:
        string: '%{[message]} - Podname=${MY_POD_NAME}}'
        pretty: false
    queue.mem:
      events: 65536
    logging.metrics.enabled: false
