kind: Service
apiVersion: v1
metadata:
  name: auth-proxy-server
  namespace: auth
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: auth-proxy-server
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: auth-proxy-server
  name: auth-proxy-server
  namespace: auth
spec:
  selector:
    matchLabels:
      app: auth-proxy-server
  replicas: 2
  template:
    metadata:
      labels:
        app: auth-proxy-server
        env: k8s-mon
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "9091"
    spec:
      containers:
      #- image: cmssw/auth-proxy-server:0.1.81
      #- image: cmssw/auth-proxy-server:0.1.106
#       - image: cmssw/auth-proxy-server:0.1.106-static
      - image: cmssw/auth-proxy-server:0.2.07
        name: auth-proxy-server
        imagePullPolicy: Always
        args:
          - /data/auth-proxy-server
          - -config=/etc/secrets/config.json
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "3Gi"
            cpu: "4000m"
        env:
        - name: X509_USER_PROXY
          value: /etc/proxy/proxy
        ports:
        - containerPort: 443
          name: https
        - containerPort: 9091
          name: metrics
        volumeMounts:
        - name: auth-secrets
          mountPath: /etc/secrets
          defaultMode: 256
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
      volumes:
      - name: auth-secrets
        secret:
          secretName: auth-secrets
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: hostcert
        hostPath:
            path: /etc/grid-security/hostcert.pem
      - name: hostkey
        hostPath:
            path: /etc/grid-security/hostkey.pem
