apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqoop
  namespace: sqoop
  labels:
     app: sqoop
spec:
   replicas: 1
   selector:
     matchLabels:
       app: sqoop
   template:
      metadata:
         labels:
           app: sqoop
      spec:
        containers:
        - args:
          - /data/sqoop/daemon.sh
          - /data/sqoop/log
          - "7"
          - "7200"
          image: cmssw/sqoop:20210715
          #image: cmssw/sqoop:20210323-v2
          #image: cmssw/sqoop:20210212
          #image: cmssw/sqoop:20210208
          #image: cmssw/sqoop:20201214
          name: sqoop
          volumeMounts:
          - name: sqoop-secrets
            mountPath: /etc/cmsdb
            readOnly: true
          - name: rucio-secrets
            mountPath: /etc/secrets
            readOnly: true
        volumes:
        - name: sqoop-secrets
          secret:
            secretName: sqoop-secrets
        - name: rucio-secrets
          secret:
            secretName: rucio-secrets
