apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-http
  namespace: http
  annotations:
    kubernetes.io/ingress.class: nginx
    # restrict access to this ingress controller from specific IPs
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#whitelist-source-range
    nginx.ingress.kubernetes.io/whitelist-source-range: 188.185.101.116,188.184.75.82,188.184.89.113,188.184.73.32,188.185.89.202,188.185.89.194,188.185.114.255,188.185.25.202,137.138.54.240,188.184.117.46,188.185.29.242,188.185.31.221,188.185.30.204,188.185.18.13,188.185.14.65,188.185.81.186
#    nginx.ingress.kubernetes.io/affinity: "cookie"
#    nginx.ingress.kubernetes.io/session-cookie-name: "route"
#    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
#    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  rules:
  - host: cmsweb-srv.cern.ch
    http:
      paths:
      - path: /exitcodes
        pathType: Prefix
        backend:
          service:
            name: exitcodes
            port: 
              number: 9201
      - path: /httpgo
        pathType: Prefix
        backend:
          service:
            name: httpgo
            port:
              number: 8888
      - path: /httpsgo
        pathType: Prefix
        backend:
          service:
            name: httpsgo
            port:
              number: 443
      - path: /cmskv
        pathType: Prefix
        backend:
          service:
            name: cmskv
            port:
              number: 9212
      - path: /cmsamqproxy
        pathType: Prefix
        backend:
          service:
            name: cmsamqproxy
            port:
              number: 8300
